### ISSUE TITLE
Implement ability to designate type of site for domains within vars.yml

### ISSUE THREAD

**Issue by nerrad** [nerrad/wordpress-ansible-playbook#5]
Since the nginx repo provides configuration for WP multisite, and we're using wp-cli to install WP, it should be trivial to control what type of site is setup for the given domains (i.e. multisite-subdomain/multisite-subfolder/single-site)

One way of doing this would be to have people define their domains as an object.  Something like this:

```yml
main_domain:
    type: single-site
    name: mysite.com
```
