### ISSUE TITLE
Set a fact for complex things like paths that are used in multiple places.

### ISSUE THREAD

**Issue by nerrad** [nerrad/wordpress-ansible-playbook#6]
Something that is used frequently in the tasks across roles for this playbook is the path for a domain

```
/home/{{ remote_web_user }}/www/{{ domain }}
```

It could be useful if I set a fact for this which can then be reused across the roles.  I can put this in its own config file.  Something like: `set-facts.yml` which would have something like this for the contents:

```yml
---
- name: setting reusable facts for role
   set_fact:
     -  user_path: /home/{{ remote_web_user }}/www/{{ domain }}
   when: remote_user is defined and domain is defined
```

Then in the role configuration I can just do:

```yml
---
# tasks file for common role facts
- include: "{{wpa_root_path}}/set-facts.yml"
```

**Note**: because of the funky way ansible searches includes, it'll be less problematic if in the main playbook I set a "wpa_root_path" variable that can then prefix any include paths.  So this would look something like this:

```yml
wpa_root_path: "{{ playbook_dir }}"
```
